// game_rules.js

// --- SKILLS ---
const SKILLS_LIST = {
    "Acrobatics": "DEX", "Animal Handling": "WIS", "Arcana": "INT", "Athletics": "STR", 
    "Deception": "CHA", "History": "INT", "Insight": "WIS", "Intimidation": "CHA", 
    "Investigation": "INT", "Medicine": "WIS", "Nature": "INT", "Perception": "WIS", 
    "Performance": "CHA", "Persuasion": "CHA", "Religion": "INT", "Sleight of Hand": "DEX", 
    "Stealth": "DEX", "Survival": "WIS"
};

// --- RACES ---
const RACES = {
    "Human": { bonuses: {STR: 1, DEX: 1, CON: 1, INT: 1, WIS: 1, CHA: 1}, hp_bonus: 0 },
    "High Elf": { bonuses: {DEX: 2, INT: 1}, hp_bonus: 0 },
    "Wood Elf": { bonuses: {DEX: 2, WIS: 1}, hp_bonus: 0 },
    "Drow": { bonuses: {DEX: 2, CHA: 1}, hp_bonus: 0 },
    "Hill Dwarf": { bonuses: {CON: 2, WIS: 1}, hp_bonus: 1 },
    "Mountain Dwarf": { bonuses: {STR: 2, CON: 2}, hp_bonus: 0 },
    "Lightfoot Halfling": { bonuses: {DEX: 2, CHA: 1}, hp_bonus: 0 },
    "Stout Halfling": { bonuses: {DEX: 2, CON: 1}, hp_bonus: 0 },
    "Dragonborn": { bonuses: {STR: 2, CHA: 1}, hp_bonus: 0 },
    "Tiefling": { bonuses: {CHA: 2, INT: 1}, hp_bonus: 0 },
    "Half-Orc": { bonuses: {STR: 2, CON: 1}, hp_bonus: 0 },
    "Gnome (Forest)": { bonuses: {INT: 2, DEX: 1}, hp_bonus: 0 },
    "Gnome (Rock)": { bonuses: {INT: 2, CON: 1}, hp_bonus: 0 },
    "Half-Elf": { bonuses: {CHA: 2, DEX: 1, CON: 1}, hp_bonus: 0 },
    "Goliath": { bonuses: {STR: 2, CON: 1}, hp_bonus: 0 },
    "Firbolg": { bonuses: {WIS: 2, STR: 1}, hp_bonus: 0 },
    "Tabaxi": { bonuses: {DEX: 2, CHA: 1}, hp_bonus: 0 },
    "Tortle": { bonuses: {STR: 2, WIS: 1}, hp_bonus: 0 },
    "Warforged": { bonuses: {CON: 2, STR: 1}, hp_bonus: 0 },
    "Aasimar": { bonuses: {CHA: 2}, hp_bonus: 0 },
    "Genasi (Fire)": { bonuses: {CON: 2, INT: 1}, hp_bonus: 0 },
    "Genasi (Water)": { bonuses: {CON: 2, WIS: 1}, hp_bonus: 0 }
};

// --- CLASSES ---
const CLASSES = {
    "Artificer": { hit_die: 8, saves: ["CON", "INT"], items: ["Light Crossbow", "Scale Mail", "Thieves' Tools"] },
    "Barbarian": { hit_die: 12, saves: ["STR", "CON"], items: ["Greataxe", "Handaxe", "Javelin"] },
    "Bard": { hit_die: 8, saves: ["DEX", "CHA"], items: ["Rapier", "Leather Armor", "Dagger"] },
    "Cleric": { hit_die: 8, saves: ["WIS", "CHA"], items: ["Mace", "Scale Mail", "Shield"] },
    "Druid": { hit_die: 8, saves: ["INT", "WIS"], items: ["Scimitar", "Leather Armor", "Shield"] },
    "Fighter": { hit_die: 10, saves: ["STR", "CON"], items: ["Chain Mail", "Longsword", "Shield"] },
    "Monk": { hit_die: 8, saves: ["STR", "DEX"], items: ["Shortsword", "Dart"] },
    "Paladin": { hit_die: 10, saves: ["WIS", "CHA"], items: ["Longsword", "Shield", "Chain Mail"] },
    "Ranger": { hit_die: 10, saves: ["STR", "DEX"], items: ["Scale Mail", "Shortsword", "Longbow"] },
    "Rogue": { hit_die: 8, saves: ["DEX", "INT"], items: ["Rapier", "Shortbow", "Leather Armor"] },
    "Sorcerer": { hit_die: 6, saves: ["CON", "CHA"], items: ["Light Crossbow", "Dagger"] },
    "Warlock": { hit_die: 8, saves: ["WIS", "CHA"], items: ["Light Crossbow", "Leather Armor"] },
    "Wizard": { hit_die: 6, saves: ["INT", "WIS"], items: ["Dagger", "Quarterstaff"] }
};

// --- SUBCLASS FEATURES (Simplified for JS) ---
const SUBCLASS_FEATURES = [
    {name: "Eldritch Cannon", dice: "-", type: "Action", category: "Feature", action_type: "Bonus Action", desc: "Create a cannon that shoots force/fire or grants THP."},
    {name: "Steel Defender", dice: "-", type: "Pet", category: "Feature", action_type: "Passive", desc: "Construct companion. Attacks on your BA."},
    {name: "Battle Ready", dice: "INT", type: "Int for Atk", category: "Feature", action_type: "Passive", desc: "Use Int for magic weapon attacks."},
    {name: "Ancestral Protectors", dice: "-", type: "Debuff", category: "Feature", action_type: "Passive", desc: "First creature you hit has disadvantage on attacks vs others."},
    {name: "Battlerager Armor", dice: "1d4", type: "Piercing", category: "Feature", action_type: "Bonus Action", desc: "Attack with spiked armor as a bonus action."},
    {name: "Form of the Beast", dice: "1d6", type: "Varies", category: "Feature", action_type: "Action", desc: "Gain Bite, Claws, or Tail while raging."},
    {name: "Storm Aura", dice: "2", type: "Damage", category: "Feature", action_type: "Bonus Action", desc: "Aura effect (Desert/Sea/Tundra) activates on Rage/BA."},
    {name: "Wild Surge", dice: "-", type: "Effect", category: "Feature", action_type: "Action", desc: "Random magical effect when you Rage."},
    {name: "Divine Fury", dice: "1d6", type: "Necrotic", category: "Feature", action_type: "Free", desc: "First hit on turn deals extra radiant/necrotic damage (+Level)."},
    {name: "Mote of Potential", dice: "-", type: "Buff", category: "Feature", action_type: "Bonus Action", desc: "Bardic Inspiration adds extra effects based on roll type."},
    {name: "Silver Tongue", dice: "-", type: "Advantage", category: "Feature", action_type: "Passive", desc: "Treat d20 roll of 9 or lower as 10 for Persuasion/Deception."},
    {name: "Mantle of Inspiration", dice: "-", type: "Temp HP", category: "Feature", action_type: "Bonus Action", desc: "Grant allies Temp HP and movement."},
    {name: "Tales from Beyond", dice: "-", type: "Random", category: "Feature", action_type: "Bonus Action", desc: "Roll on Spirit Table for effect."},
    {name: "Blade Flourish", dice: "1d6", type: "Damage", category: "Feature", action_type: "Free", desc: "Add Bardic Die to damage + AC/Push/Mobile."},
    {name: "Psychic Blades", dice: "2d6", type: "Psychic", category: "Feature", action_type: "Free", desc: "Expend Inspiration to deal psychic damage on hit."},
    {name: "Arcane Initiate", dice: "-", type: "Cantrip", category: "Feature", action_type: "Passive", desc: "Gain 2 Wizard cantrips."},
    {name: "Reaper", dice: "-", type: "Cantrip", category: "Feature", action_type: "Passive", desc: "Necromancy cantrips hit two targets if within 5ft."},
    {name: "Blessing of the Forge", dice: "1", type: "AC/Atk", category: "Feature", action_type: "Action", desc: "Make weapon or armor +1 until long rest."},
    {name: "Circle of Mortality", dice: "-", type: "Max Heal", category: "Feature", action_type: "Passive", desc: "Healing spells on 0 HP targets do max possible healing."},
    {name: "Blessings of Knowledge", dice: "-", type: "Skills", category: "Feature", action_type: "Passive", desc: "Proficiency and Expertise in 2 skills."},
    {name: "Acolyte of Nature", dice: "-", type: "Cantrip", category: "Feature", action_type: "Passive", desc: "Druid cantrip + Skill."},
    {name: "Voice of Authority", dice: "-", type: "Reaction", category: "Feature", action_type: "Passive", desc: "Ally you target with spell can make reaction attack."},
    {name: "Emboldening Bond", dice: "1d4", type: "Buff", category: "Feature", action_type: "Action", desc: "Bonded allies add d4 to attacks/saves/checks."},
    {name: "Blessing of the Trickster", dice: "-", type: "Stealth", category: "Feature", action_type: "Action", desc: "Grant Advantage on Stealth to another creature."},
    {name: "Eyes of Night", dice: "-", type: "Darkvision", category: "Feature", action_type: "Passive", desc: "300ft Darkvision, shareable."},
    {name: "Vigilant Blessing", dice: "-", type: "Adv Init", category: "Feature", action_type: "Action", desc: "Grant Advantage on Initiative to one creature."},
    {name: "War Priest", dice: "-", type: "Bonus Atk", category: "Feature", action_type: "Bonus Action", desc: "Make weapon attack as Bonus Action (Wis mod/day)."},
    {name: "Balm of the Summer Court", dice: "1d6", type: "Healing", category: "Feature", action_type: "Bonus Action", desc: "Pool of d6s to heal allies."},
    {name: "Spirit Totem", dice: "-", type: "Aura", category: "Feature", action_type: "Bonus Action", desc: "Summon spirit (Bear/Hawk/Unicorn) aura."},
    {name: "Symbiotic Entity", dice: "1d6", type: "Necrotic", category: "Feature", action_type: "Action", desc: "Gain Temp HP and deal extra damage while active."},
    {name: "Starry Form", dice: "-", type: "Transform", category: "Feature", action_type: "Bonus Action", desc: "Archer, Chalice, or Dragon form benefits."},
    {name: "Summon Wildfire Spirit", dice: "-", type: "Pet", category: "Feature", action_type: "Action", desc: "Summon flame spirit that shoots fire."},
    {name: "Arcane Shot", dice: "2d6", type: "Magical", category: "Feature", action_type: "Free", desc: "Apply magical effect to arrow (2/rest)."},
    {name: "Rallying Cry", dice: "-", type: "Healing", category: "Feature", action_type: "Bonus Action", desc: "Heal allies when using Second Wind."},
    {name: "Unwavering Mark", dice: "-", type: "Mark", category: "Feature", action_type: "Free", desc: "Mark target. Disadvantage to attack others."},
    {name: "Manifest Echo", dice: "-", type: "Summon", category: "Feature", action_type: "Bonus Action", desc: "Create echo. Teleport, attack from its space."},
    {name: "Spellcasting (EK)", dice: "-", type: "Spells", category: "Feature", action_type: "Passive", desc: "Learn Wizard spells (Abjuration/Evocation)."},
    {name: "Weapon Bond", dice: "-", type: "Utility", category: "Feature", action_type: "Action", desc: "Summon weapon to hand."},
    {name: "Psionic Power", dice: "1d6", type: "Damage/Red", category: "Feature", action_type: "Free", desc: "Psionic dice to reduce damage or add force damage."},
    {name: "Rune Carver", dice: "-", type: "Buff", category: "Feature", action_type: "Action", desc: "Inscribe runes on gear for passive/active effects."},
    {name: "Fighting Spirit", dice: "-", type: "Advantage", category: "Feature", action_type: "Bonus Action", desc: "Advantage on all attacks this turn + Temp HP."},
    {name: "Draconic Disciple", dice: "-", type: "Breath", category: "Feature", action_type: "Action", desc: "Breath weapon or change unarmed damage type."},
    {name: "Arms of the Astral Self", dice: "1d4", type: "Force", category: "Feature", action_type: "Bonus Action", desc: "Spectral arms. Reach +5ft, use Wis for Str checks."},
    {name: "Drunken Technique", dice: "-", type: "Speed", category: "Feature", action_type: "Passive", desc: "Flurry of Blows gives Disengage + 10ft speed."},
    {name: "Disciple of the Elements", dice: "-", type: "Spells", category: "Feature", action_type: "Action", desc: "Cast elemental spells with Ki."},
    {name: "Kensei Weapons", dice: "-", type: "Buff", category: "Feature", action_type: "Passive", desc: "Weapons count as Monk weapons. +2 AC if unarmed strike used."},
    {name: "Agile Parry", dice: "2", type: "AC", category: "Feature", action_type: "Passive", desc: "+2 AC if holding Kensei weapon and make unarmed strike."},
    {name: "Touch of Death", dice: "-", type: "Temp HP", category: "Feature", action_type: "Passive", desc: "Gain Temp HP when reducing foe to 0 HP."},
    {name: "Hand of Healing", dice: "1d4", type: "Healing", category: "Feature", action_type: "Action", desc: "Spend Ki to heal ally."},
    {name: "Hand of Harm", dice: "1d4", type: "Necrotic", category: "Feature", action_type: "Action", desc: "Spend Ki to deal extra necrotic damage."},
    {name: "Radiant Sun Bolt", dice: "1d4", type: "Radiant", category: "Feature", action_type: "Action", desc: "Ranged spell attack (30ft)."},
    {name: "Nature's Wrath", dice: "-", type: "Restrain", category: "Feature", action_type: "Channel Divinity", desc: "Vines restrain creature."},
    {name: "Conquering Presence", dice: "-", type: "Fear", category: "Feature", action_type: "Channel Divinity", desc: "Frighten enemies within 30ft."},
    {name: "Champion Challenge", dice: "-", type: "Control", category: "Feature", action_type: "Channel Divinity", desc: "Enemies cannot move more than 30ft away."},
    {name: "Peerless Athlete", dice: "-", type: "Advantage", category: "Feature", action_type: "Channel Divinity", desc: "Advantage on Athletics/Acrobatics. Jump distance +10ft."},
    {name: "Emissary of Peace", dice: "5", type: "Persuasion", category: "Feature", action_type: "Channel Divinity", desc: "+5 to Persuasion for 10 mins."},
    {name: "Watcher's Will", dice: "-", type: "Save Adv", category: "Feature", action_type: "Channel Divinity", desc: "Advantage on INT/WIS/CHA saves for allies."},
    {name: "Control Undead", dice: "-", type: "Control", category: "Feature", action_type: "Channel Divinity", desc: "Force undead to obey commands."},
    {name: "Drake Companion", dice: "-", type: "Pet", category: "Feature", action_type: "Action", desc: "Summon small dragon companion."},
    {name: "Dreadful Strikes", dice: "1d4", type: "Psychic", category: "Feature", action_type: "Free", desc: "Deal extra damage once per turn per target."},
    {name: "Dread Ambusher", dice: "1d8", type: "Bonus Dmg", category: "Feature", action_type: "Passive", desc: "First turn: +10 speed, extra attack deals +1d8."},
    {name: "Planar Warrior", dice: "1d8", type: "Force", category: "Feature", action_type: "Bonus Action", desc: "Next hit converts all damage to Force + 1d8."},
    {name: "Hunter's Sense", dice: "-", type: "Info", category: "Feature", action_type: "Action", desc: "Learn immunities/resistances of target."},
    {name: "Gathered Swarm", dice: "1d6", type: "Piercing", category: "Feature", action_type: "Free", desc: "Add damage or move self/enemy on hit."},
    {name: "Spellcasting (AT)", dice: "-", type: "Spells", category: "Feature", action_type: "Passive", desc: "Learn Wizard spells (Enchantment/Illusion)."},
    {name: "Ear for Deceit", dice: "-", type: "Min 10", category: "Feature", action_type: "Passive", desc: "Minimum roll of 8 on Insight."},
    {name: "Master of Tactics", dice: "-", type: "Help", category: "Feature", action_type: "Bonus Action", desc: "Help action as Bonus Action, range 30ft."},
    {name: "Whispers of the Dead", dice: "-", type: "Prof", category: "Feature", action_type: "Passive", desc: "Gain proficiency in one skill/tool on long rest."},
    {name: "Skirmisher", dice: "-", type: "Reaction Move", category: "Feature", action_type: "Reaction", desc: "Move half speed when enemy ends turn within 5ft."},
    {name: "Fancy Footwork", dice: "-", type: "Disengage", category: "Feature", action_type: "Passive", desc: "Don't provoke OA from creature you attack."},
    {name: "Telepathic Speech", dice: "-", type: "Comm", category: "Feature", action_type: "Bonus Action", desc: "Telepathic link with creature for minutes."},
    {name: "Restore Balance", dice: "-", type: "Neut Adv/Dis", category: "Feature", action_type: "Reaction", desc: "Cancel Advantage or Disadvantage on a roll."},
    {name: "Favored by the Gods", dice: "2d4", type: "Save Bonus", category: "Feature", action_type: "Free", desc: "Add 2d4 to failed save or attack roll (1/rest)."},
    {name: "Draconic Resilience", dice: "-", type: "AC 13", category: "Feature", action_type: "Passive", desc: "AC 13 + Dex. +1 HP per level."},
    {name: "Eyes of the Dark", dice: "-", type: "Darkvision", category: "Feature", action_type: "Passive", desc: "120ft Darkvision (magical)."},
    {name: "Tempestuous Magic", dice: "-", type: "Fly 10ft", category: "Feature", action_type: "Bonus Action", desc: "Fly 10ft without provoking OAs after casting lvl 1+ spell."},
    {name: "Fey Presence", dice: "-", type: "Charm/Fear", category: "Feature", action_type: "Action", desc: "10ft cube charm or fear."},
    {name: "Healing Light", dice: "1d6", type: "Healing", category: "Feature", action_type: "Bonus Action", desc: "Pool of d6s to heal range 60ft."},
    {name: "Tentacle of the Deeps", dice: "1d8", type: "Cold", category: "Feature", action_type: "Bonus Action", desc: "Summon tentacle that attacks and slows."},
    {name: "Genie's Vessel", dice: "-", type: "Storage", category: "Feature", action_type: "Action", desc: "Bottled Respite or Genies Wrath (+PB dmg)."},
    {name: "Awakened Mind", dice: "-", type: "Telepathy", category: "Feature", action_type: "Passive", desc: "Telepathy 30ft."},
    {name: "Form of Dread", dice: "-", type: "Temp HP/Fear", category: "Feature", action_type: "Bonus Action", desc: "Transform: Temp HP + Frighten on hit."},
    {name: "Among the Dead", dice: "-", type: "Sanctuary", category: "Feature", action_type: "Passive", desc: "Undead have to save to attack you."},
    {name: "Arcane Ward", dice: "-", type: "Shield HP", category: "Feature", action_type: "Passive", desc: "Ward absorbs damage."},
    {name: "Bladesong", dice: "-", type: "AC/Conc", category: "Feature", action_type: "Bonus Action", desc: "+Int to AC, +10 speed, Adv Acrobatics, +Int to Conc."},
    {name: "Chronal Shift", dice: "-", type: "Reroll", category: "Feature", action_type: "Reaction", desc: "Force reroll of attack, check, or save (2/day)."},
    {name: "Minor Conjuration", dice: "-", type: "Create Item", category: "Feature", action_type: "Action", desc: "Create small non-magical object."},
    {name: "Portent", dice: "-", type: "Dice Sub", category: "Feature", action_type: "Free", desc: "Roll 2d20 at start of day, replace any roll."},
    {name: "Hypnotic Gaze", dice: "-", type: "Incap", category: "Feature", action_type: "Action", desc: "Charm/Incapacitate creature within 5ft."},
    {name: "Adjust Density", dice: "-", type: "Speed/Weight", category: "Feature", action_type: "Action", desc: "Halve/Double weight/speed of creature."},
    {name: "Improved Minor Illusion", dice: "-", type: "Sound+Image", category: "Feature", action_type: "Passive", desc: "Minor Illusion creates both sound and image."},
    {name: "Wizardly Quill", dice: "-", type: "Scribe", category: "Feature", action_type: "Passive", desc: "Copy spells faster (2 mins/level)."},
    {name: "Minor Alchemy", dice: "-", type: "Transmute", category: "Feature", action_type: "Action", desc: "Change material (wood to stone, etc)."},
    {name: "Arcane Deflection", dice: "2", type: "AC", category: "Feature", action_type: "Reaction", desc: "+2 AC or +4 Save vs one attack."},
];

// --- WEAPONS & SPELLS ---
const ALL_WEAPONS = [
    // --- WEAPONS ---
    {name: "Unarmed Strike", dice: "1", type: "Bludgeoning", category: "Simple Melee", stat: "STR", desc: "Basic melee strike."},
    {name: "Dagger", dice: "1d4", type: "Piercing", category: "Simple Melee", stat: "DEX", desc: "Finesse, light, thrown (20/60)."},
    {name: "Handaxe", dice: "1d6", type: "Slashing", category: "Simple Melee", stat: "STR", desc: "Light, thrown (20/60)."},
    {name: "Javelin", dice: "1d6", type: "Piercing", category: "Simple Melee", stat: "STR", desc: "Thrown (30/120)."},
    {name: "Mace", dice: "1d6", type: "Bludgeoning", category: "Simple Melee", stat: "STR", desc: "-"},
    {name: "Quarterstaff", dice: "1d6", type: "Bludgeoning", category: "Simple Melee", stat: "STR", desc: "Versatile (1d8)."},
    {name: "Spear", dice: "1d6", type: "Piercing", category: "Simple Melee", stat: "STR", desc: "Thrown (20/60), Versatile (1d8)."},
    {name: "Light Crossbow", dice: "1d8", type: "Piercing", category: "Simple Ranged", stat: "DEX", desc: "Ammo (80/320), loading, two-handed."},
    {name: "Dart", dice: "1d4", type: "Piercing", category: "Simple Ranged", stat: "DEX", desc: "Finesse, thrown (20/60)."},
    {name: "Shortbow", dice: "1d6", type: "Piercing", category: "Simple Ranged", stat: "DEX", desc: "Ammo (80/320), two-handed."},
    {name: "Battleaxe", dice: "1d8", type: "Slashing", category: "Martial Melee", stat: "STR", desc: "Versatile (1d10)."},
    {name: "Greataxe", dice: "1d12", type: "Slashing", category: "Martial Melee", stat: "STR", desc: "Heavy, two-handed."},
    {name: "Greatsword", dice: "2d6", type: "Slashing", category: "Martial Melee", stat: "STR", desc: "Heavy, two-handed."},
    {name: "Longsword", dice: "1d8", type: "Slashing", category: "Martial Melee", stat: "STR", desc: "Versatile (1d10)."},
    {name: "Rapier", dice: "1d8", type: "Piercing", category: "Martial Melee", stat: "DEX", desc: "Finesse."},
    {name: "Scimitar", dice: "1d6", type: "Slashing", category: "Martial Melee", stat: "DEX", desc: "Finesse, light."},
    {name: "Shortsword", dice: "1d6", type: "Piercing", category: "Martial Melee", stat: "DEX", desc: "Finesse, light."},
    {name: "Warhammer", dice: "1d8", type: "Bludgeoning", category: "Martial Melee", stat: "STR", desc: "Versatile (1d10)."},
    {name: "Hand Crossbow", dice: "1d6", type: "Piercing", category: "Martial Ranged", stat: "DEX", desc: "Ammo (30/120), light, loading."},
    {name: "Longbow", dice: "1d8", type: "Piercing", category: "Martial Ranged", stat: "DEX", desc: "Ammo (150/600), heavy, two-handed."},
    {name: "Leather Armor", dice: "-", type: "-", category: "Armor", ac: 11, armor_type: "Light", desc: "AC 11 + Dex Modifier"},
    {name: "Studded Leather", dice: "-", type: "-", category: "Armor", ac: 12, armor_type: "Light", desc: "AC 12 + Dex Modifier"},
    {name: "Scale Mail", dice: "-", type: "-", category: "Armor", ac: 14, armor_type: "Medium", desc: "AC 14 + Dex (Max 2). Disadv Stealth."},
    {name: "Chain Mail", dice: "-", type: "-", category: "Armor", ac: 16, armor_type: "Heavy", desc: "AC 16. Str 13 Req. Disadv Stealth."},
    {name: "Plate", dice: "-", type: "-", category: "Armor", ac: 18, armor_type: "Heavy", desc: "AC 18. Str 15 Req. Disadv Stealth."},
    {name: "Shield", dice: "-", type: "-", category: "Armor", ac: 2, armor_type: "Shield", desc: "+2 AC"},
    // --- FEATURES ---
    {name: "Rage", dice: "2", type: "Bonus Dmg", category: "Feature", action_type: "Bonus Action", stat: "STR", desc: "Adv Strength checks/saves. Resist Bludg/Pierc/Slash. +2 Dmg."},
    {name: "Bardic Inspiration", dice: "1d6", type: "Buff", category: "Feature", action_type: "Bonus Action", stat: "CHA", desc: "Grant ally 1d6 to add to ability check, attack, or save."},
    {name: "Second Wind", dice: "1d10", type: "Healing", category: "Feature", action_type: "Bonus Action", stat: "CON", desc: "Regain 1d10 + Level HP. Once per short rest."},
    {name: "Action Surge", dice: "-", type: "Extra Action", category: "Feature", action_type: "Free", desc: "Take one additional action on your turn."},
    {name: "Sneak Attack", dice: "1d6", type: "Bonus Dmg", category: "Feature", action_type: "Passive", scale_dice: "1d6", desc: "Extra damage once/turn if Adv or ally within 5ft."},
    {name: "Cunning Action", dice: "-", type: "Dash/Dis/Hide", category: "Feature", action_type: "Bonus Action", desc: "Bonus action to Dash, Disengage, or Hide."},
    {name: "Martial Arts", dice: "1d4", type: "Bludgeoning", category: "Feature", action_type: "Bonus Action", stat: "DEX", desc: "Use Dex for unarmed. Bonus unarmed strike after attack."},
    {name: "Ki", dice: "-", type: "Resource", category: "Feature", action_type: "Passive", desc: "Spend Ki points for Flurry of Blows, Patient Defense, etc."},
    {name: "Divine Smite", dice: "2d8", type: "Radiant", category: "Feature", action_type: "Free", stat: "CHA", desc: "Expend spell slot on hit. 2d8 + 1d8 per level above 1st."},
    {name: "Lay on Hands", dice: "-", type: "Heal", category: "Feature", action_type: "Action", desc: "Pool of HP (Level x 5). Touch to heal."},
    {name: "Wild Shape", dice: "-", type: "Transform", category: "Feature", action_type: "Action", desc: "Transform into a beast you have seen."},
    {name: "Channel Divinity", dice: "-", type: "Effect", category: "Feature", action_type: "Action", desc: "Magical effect based on your Domain/Oath."},
    {name: "Magical Tinkering", dice: "-", type: "Utility", category: "Feature", action_type: "Action", desc: "Imbue tiny object with light, audio, or message."},
    {name: "Infuse Item", dice: "-", type: "Enhance", category: "Feature", action_type: "Passive", desc: "Turn mundane items into magic items."},
    {name: "Unarmored Defense", dice: "-", type: "AC Calc", category: "Feature", action_type: "Passive", desc: "AC = 10 + Dex + Con (Barb) or Wis (Monk) when unarmored."},
    {name: "Colossus Slayer", dice: "1d8", type: "Bonus Dmg", category: "Feature", action_type: "Passive", desc: "Extra 1d8 damage if target is below max HP."},
    {name: "Thunder Gauntlets", dice: "1d8", type: "Thunder", category: "Weapon", action_type: "Action", stat: "INT", desc: "Disadvantage on attacks vs others."},
    {name: "Lightning Launcher", dice: "1d6", type: "Lightning", category: "Weapon", action_type: "Action", stat: "INT", desc: "Range 90/300. Extra 1d6 once per turn."},
    // --- SPELLS ---
    {name: "Acid Splash", dice: "1d6", type: "Acid", category: "Spell", level: 0, scale_dice: "1d6", desc: "Dex Save. Two targets within 5ft."},
    {name: "Blade Ward", dice: "-", type: "Resist", category: "Spell", level: 0, desc: "Resistance to B/P/S damage until next turn."},
    {name: "Chill Touch", dice: "1d8", type: "Necrotic", category: "Spell", level: 0, scale_dice: "1d8", desc: "Target can't heal until your next turn."},
    {name: "Dancing Lights", dice: "-", type: "Light", category: "Spell", level: 0, desc: "Create 4 lights. Conc."},
    {name: "Druidcraft", dice: "-", type: "Utility", category: "Spell", level: 0, desc: "Sensory effect, light fire, weather predict."},
    {name: "Eldritch Blast", dice: "1d10", type: "Force", category: "Spell", level: 0, scale_dice: "1d10", desc: "120ft range. Multiple beams at higher levels."},
    {name: "Fire Bolt", dice: "1d10", type: "Fire", category: "Spell", level: 0, scale_dice: "1d10", desc: "120ft range. Ranged spell attack."},
    {name: "Guidance", dice: "1d4", type: "Buff", category: "Spell", level: 0, desc: "Add 1d4 to one ability check."},
    {name: "Light", dice: "-", type: "Light", category: "Spell", level: 0, desc: "Object sheds light 20/20ft."},
    {name: "Mage Hand", dice: "-", type: "Utility", category: "Spell", level: 0, desc: "Spectral hand carries 10lbs."},
    {name: "Mending", dice: "-", type: "Utility", category: "Spell", level: 0, desc: "Repair a single break/tear."},
    {name: "Message", dice: "-", type: "Comm", category: "Spell", level: 0, desc: "Whisper message to creature 120ft."},
    {name: "Minor Illusion", dice: "-", type: "Illusion", category: "Spell", level: 0, desc: "Create sound or image 5ft cube."},
    {name: "Poison Spray", dice: "1d12", type: "Poison", category: "Spell", level: 0, scale_dice: "1d12", desc: "Con Save. 10ft range."},
    {name: "Prestidigitation", dice: "-", type: "Utility", category: "Spell", level: 0, desc: "Minor tricks, clean, warm, flavor."},
    {name: "Produce Flame", dice: "1d8", type: "Fire", category: "Spell", level: 0, scale_dice: "1d8", desc: "Light or throw for attack."},
    {name: "Ray of Frost", dice: "1d8", type: "Cold", category: "Spell", level: 0, scale_dice: "1d8", desc: "Reduces speed by 10ft."},
    {name: "Resistance", dice: "1d4", type: "Buff", category: "Spell", level: 0, desc: "Add 1d4 to one saving throw."},
    {name: "Sacred Flame", dice: "1d8", type: "Radiant", category: "Spell", level: 0, scale_dice: "1d8", desc: "Dex Save. Ignores cover."},
    {name: "Shillelagh", dice: "1d8", type: "Magical", category: "Spell", level: 0, action_type: "Bonus Action", desc: "Club/Staff becomes magical d8 weapon using Wis."},
    {name: "Shocking Grasp", dice: "1d8", type: "Lightning", category: "Spell", level: 0, scale_dice: "1d8", desc: "Touch. Adv vs Metal Armor. No reactions."},
    {name: "Spare the Dying", dice: "-", type: "Stabilize", category: "Spell", level: 0, desc: "Stabilize creature at 0 HP."},
    {name: "Thaumaturgy", dice: "-", type: "Utility", category: "Spell", level: 0, desc: "Loud voice, tremors, door slam."},
    {name: "Thorn Whip", dice: "1d6", type: "Piercing", category: "Spell", level: 0, scale_dice: "1d6", desc: "Pull creature 10ft closer."},
    {name: "True Strike", dice: "-", type: "Advantage", category: "Spell", level: 0, desc: "Advantage on next attack next turn."},
    {name: "Vicious Mockery", dice: "1d4", type: "Psychic", category: "Spell", level: 0, scale_dice: "1d4", desc: "Wis Save. Disadvantage on next attack."},
    {name: "Word of Radiance", dice: "1d6", type: "Radiant", category: "Spell", level: 0, scale_dice: "1d6", desc: "Con save. All enemies within 5ft."},
    {name: "Thunderclap", dice: "1d6", type: "Thunder", category: "Spell", level: 0, scale_dice: "1d6", desc: "Con save. 5ft radius."},
    {name: "Toll the Dead", dice: "1d8", type: "Necrotic", category: "Spell", level: 0, scale_dice: "1d8", desc: "Wis Save. d12 if damaged."},
    {name: "Alarm", dice: "-", type: "Utility", category: "Spell", level: 1, desc: "Alerts when area entered. Ritual."},
    {name: "Animal Friendship", dice: "-", type: "Charm", category: "Spell", level: 1, desc: "Charm beast INT < 4."},
    {name: "Armor of Agathys", dice: "5", type: "Cold", category: "Spell", level: 1, scale_dice: "5", desc: "Gain 5 THP. Hitters take 5 Cold dmg."},
    {name: "Arms of Hadar", dice: "2d6", type: "Necrotic", category: "Spell", level: 1, scale_dice: "1d6", desc: "Str save. No reactions."},
    {name: "Bane", dice: "1d4", type: "Debuff", category: "Spell", level: 1, desc: "Cha save. Subtract d4 from attacks/saves."},
    {name: "Bless", dice: "1d4", type: "Buff", category: "Spell", level: 1, desc: "Add d4 to attacks/saves. Conc."},
    {name: "Burning Hands", dice: "3d6", type: "Fire", category: "Spell", level: 1, scale_dice: "1d6", desc: "15ft cone. Dex half."},
    {name: "Charm Person", dice: "-", type: "Charm", category: "Spell", level: 1, desc: "Wis save. Friendly acquaintance."},
    {name: "Chromatic Orb", dice: "3d8", type: "Variable", category: "Spell", level: 1, scale_dice: "1d8", desc: "Choose Acid/Cold/Fire/Lightning/Poison/Thunder."},
    {name: "Command", dice: "-", type: "Control", category: "Spell", level: 1, desc: "Wis save. Flee/Drop/Halt."},
    {name: "Compelled Duel", dice: "-", type: "Control", category: "Spell", level: 1, desc: "Wis save. Disadv attacking others."},
    {name: "Comprehend Languages", dice: "-", type: "Utility", category: "Spell", level: 1, desc: "Understand spoken/written."},
    {name: "Create or Destroy Water", dice: "-", type: "Utility", category: "Spell", level: 1, desc: "10 gallons."},
    {name: "Cure Wounds", dice: "1d8", type: "Healing", category: "Spell", level: 1, scale_dice: "1d8", desc: "Touch heal + Mod."},
    {name: "Detect Evil and Good", dice: "-", type: "Detection", category: "Spell", level: 1, desc: "Know loc of aberration/celestial/elemental/fey/fiend/undead."},
    {name: "Detect Magic", dice: "-", type: "Detection", category: "Spell", level: 1, desc: "See magical auras."},
    {name: "Detect Poison and Disease", dice: "-", type: "Detection", category: "Spell", level: 1, desc: "Sense poison/disease."},
    {name: "Disguise Self", dice: "-", type: "Illusion", category: "Spell", level: 1, desc: "Change appearance 1hr."},
    {name: "Dissonant Whispers", dice: "3d6", type: "Psychic", category: "Spell", level: 1, scale_dice: "1d6", desc: "Wis save. Reaction move away."},
    {name: "Divine Favor", dice: "1d4", type: "Radiant", category: "Spell", level: 1, action_type: "Bonus Action", desc: "Extra damage on hits."},
    {name: "Entangle", dice: "-", type: "Restrain", category: "Spell", level: 1, desc: "Str save. Difficult terrain."},
    {name: "Expeditious Retreat", dice: "-", type: "Dash", category: "Spell", level: 1, action_type: "Bonus Action", desc: "Dash as BA."},
    {name: "Faerie Fire", dice: "-", type: "Advantage", category: "Spell", level: 1, desc: "Dex save. Adv on attacks vs target."},
    {name: "False Life", dice: "1d4", type: "Temp HP", category: "Spell", level: 1, desc: "Gain 1d4 + 4 THP."},
    {name: "Feather Fall", dice: "-", type: "Safety", category: "Spell", level: 1, action_type: "Reaction", desc: "Slow fall 5 creatures."},
    {name: "Find Familiar", dice: "-", type: "Summon", category: "Spell", level: 1, desc: "Ritual. Summon spirit animal."},
    {name: "Fog Cloud", dice: "-", type: "Obscurement", category: "Spell", level: 1, desc: "Heavy obscurement."},
    {name: "Goodberry", dice: "1", type: "Healing", category: "Spell", level: 1, desc: "10 berries, 1 HP each."},
    {name: "Grease", dice: "-", type: "Prone", category: "Spell", level: 1, desc: "Dex save. Prone."},
    {name: "Guiding Bolt", dice: "4d6", type: "Radiant", category: "Spell", level: 1, scale_dice: "1d6", desc: "Advantage on next attack vs target."},
    {name: "Healing Word", dice: "1d4", type: "Healing", category: "Spell", level: 1, action_type: "Bonus Action", scale_dice: "1d4", desc: "Ranged BA heal."},
    {name: "Hellish Rebuke", dice: "2d10", type: "Fire", category: "Spell", level: 1, action_type: "Reaction", scale_dice: "1d10", desc: "Dex save half."},
    {name: "Heroism", dice: "-", type: "Buff", category: "Spell", level: 1, desc: "Immune fear, gain THP each turn."},
    {name: "Hex", dice: "1d6", type: "Necrotic", category: "Spell", level: 1, action_type: "Bonus Action", desc: "Extra dmg, Disadv on chosen ability checks."},
    {name: "Hunter's Mark", dice: "1d6", type: "Damage", category: "Spell", level: 1, action_type: "Bonus Action", desc: "Extra dmg, Adv tracking."},
    {name: "Identify", dice: "-", type: "Info", category: "Spell", level: 1, desc: "Learn magic properties."},
    {name: "Inflict Wounds", dice: "3d10", type: "Necrotic", category: "Spell", level: 1, scale_dice: "1d10", desc: "Melee spell attack."},
    {name: "Jump", dice: "-", type: "Movement", category: "Spell", level: 1, desc: "Triple jump distance."},
    {name: "Longstrider", dice: "-", type: "Speed", category: "Spell", level: 1, desc: "+10ft speed."},
    {name: "Mage Armor", dice: "-", type: "AC 13", category: "Spell", level: 1, desc: "AC becomes 13 + Dex."},
    {name: "Magic Missile", dice: "3d4", type: "Force", category: "Spell", level: 1, scale_dice: "1d4", desc: "Auto-hit darts."},
    {name: "Protection from Evil and Good", dice: "-", type: "Buff", category: "Spell", level: 1, desc: "Disadv on attacks against you by types."},
    {name: "Purify Food and Drink", dice: "-", type: "Utility", category: "Spell", level: 1, desc: "Remove poison/disease."},
    {name: "Sanctuary", dice: "-", type: "Protection", category: "Spell", level: 1, action_type: "Bonus Action", desc: "Wis save to attack target."},
    {name: "Shield", dice: "-", type: "+5 AC", category: "Spell", level: 1, action_type: "Reaction", desc: "+5 AC vs trigger attack."},
    {name: "Shield of Faith", dice: "-", type: "+2 AC", category: "Spell", level: 1, action_type: "Bonus Action", desc: "+2 AC."},
    {name: "Silent Image", dice: "-", type: "Illusion", category: "Spell", level: 1, desc: "Visual illusion."},
    {name: "Sleep", dice: "5d8", type: "Sleep", category: "Spell", level: 1, scale_dice: "2d8", desc: "Sleep by HP pool."},
    {name: "Speak with Animals", dice: "-", type: "Comm", category: "Spell", level: 1, desc: "Talk to beasts."},
    {name: "Tasha's Hideous Laughter", dice: "-", type: "Prone", category: "Spell", level: 1, desc: "Wis save. Incapacitated/Prone."},
    {name: "Thunderwave", dice: "2d8", type: "Thunder", category: "Spell", level: 1, scale_dice: "1d8", desc: "15ft cube. Con save push 10ft."},
    {name: "Unseen Servant", dice: "-", type: "Utility", category: "Spell", level: 1, desc: "Invisible force performs tasks."},
    {name: "Witch Bolt", dice: "1d12", type: "Lightning", category: "Spell", level: 1, scale_dice: "1d12", desc: "Sustained damage each turn."},
    {name: "Acid Arrow", dice: "4d4", type: "Acid", category: "Spell", level: 2, scale_dice: "2d4", desc: "And 2d4 next turn."},
    {name: "Aid", dice: "-", type: "Max HP", category: "Spell", level: 2, desc: "+5 Max HP to 3 targets."},
    {name: "Alter Self", dice: "-", type: "Buff", category: "Spell", level: 2, desc: "Change appearance or natural weapons."},
    {name: "Animal Messenger", dice: "-", type: "Comm", category: "Spell", level: 2, desc: "Send message via beast."},
    {name: "Arcane Lock", dice: "-", type: "Utility", category: "Spell", level: 2, desc: "Magically lock door."},
    {name: "Augury", dice: "-", type: "Divination", category: "Spell", level: 2, desc: "Predict future outcome."},
    {name: "Barkskin", dice: "-", type: "AC 16", category: "Spell", level: 2, desc: "AC cannot be less than 16."},
    {name: "Blindness/Deafness", dice: "-", type: "Debuff", category: "Spell", level: 2, desc: "Con save."},
    {name: "Blur", dice: "-", type: "Defense", category: "Spell", level: 2, desc: "Disadv on attacks vs you."},
    {name: "Calm Emotions", dice: "-", type: "Control", category: "Spell", level: 2, desc: "Suppress charm/fear."},
    {name: "Cloud of Daggers", dice: "4d4", type: "Slashing", category: "Spell", level: 2, scale_dice: "2d4", desc: "5ft cube area damage."},
    {name: "Continual Flame", dice: "-", type: "Light", category: "Spell", level: 2, desc: "Permanent torch."},
    {name: "Darkness", dice: "-", type: "Obscurement", category: "Spell", level: 2, desc: "15ft radius magical darkness."},
    {name: "Darkvision", dice: "-", type: "Sense", category: "Spell", level: 2, desc: "60ft Darkvision."},
    {name: "Detect Thoughts", dice: "-", type: "Info", category: "Spell", level: 2, desc: "Read surface thoughts."},
    {name: "Enhance Ability", dice: "-", type: "Buff", category: "Spell", level: 2, desc: "Advantage on checks."},
    {name: "Enlarge/Reduce", dice: "-", type: "Size", category: "Spell", level: 2, desc: "Size change +/- d4 dmg."},
    {name: "Enthrall", dice: "-", type: "Distract", category: "Spell", level: 2, desc: "Distract creatures."},
    {name: "Find Steed", dice: "-", type: "Summon", category: "Spell", level: 2, desc: "Summon spirit mount."},
    {name: "Find Traps", dice: "-", type: "Detection", category: "Spell", level: 2, desc: "Sense traps line of sight."},
    {name: "Flame Blade", dice: "3d6", type: "Fire", category: "Spell", level: 2, scale_dice: "1d6", desc: "Melee spell attack."},
    {name: "Flaming Sphere", dice: "2d6", type: "Fire", category: "Spell", level: 2, scale_dice: "1d6", desc: "Moveable ball of fire."},
    {name: "Gentle Repose", dice: "-", type: "Utility", category: "Spell", level: 2, desc: "Preserve corpse."},
    {name: "Gust of Wind", dice: "-", type: "Control", category: "Spell", level: 2, desc: "Push 15ft."},
    {name: "Heat Metal", dice: "2d8", type: "Fire", category: "Spell", level: 2, scale_dice: "1d8", desc: "Damage and Disadv if holding."},
    {name: "Hold Person", dice: "-", type: "Paralyze", category: "Spell", level: 2, desc: "Wis save. Humanoid only."},
    {name: "Invisibility", dice: "-", type: "Invisible", category: "Spell", level: 2, desc: "Ends if you attack/cast."},
    {name: "Knock", dice: "-", type: "Unlock", category: "Spell", level: 2, desc: "Open lock."},
    {name: "Lesser Restoration", dice: "-", type: "Cure", category: "Spell", level: 2, desc: "Cure disease/condition."},
    {name: "Levitate", dice: "-", type: "Float", category: "Spell", level: 2, desc: "Rise 20ft."},
    {name: "Locate Animals or Plants", dice: "-", type: "Detection", category: "Spell", level: 2, desc: "Find specific beast/plant."},
    {name: "Locate Object", dice: "-", type: "Detection", category: "Spell", level: 2, desc: "Find specific object."},
    {name: "Magic Mouth", dice: "-", type: "Utility", category: "Spell", level: 2, desc: "Message trigger."},
    {name: "Magic Weapon", dice: "-", type: "Buff", category: "Spell", level: 2, desc: "Weapon becomes +1."},
    {name: "Mirror Image", dice: "-", type: "Defense", category: "Spell", level: 2, desc: "Duplicates absorb hits."},
    {name: "Misty Step", dice: "-", type: "Teleport", category: "Spell", level: 2, action_type: "Bonus Action", desc: "30ft teleport."},
    {name: "Moonbeam", dice: "2d10", type: "Radiant", category: "Spell", level: 2, scale_dice: "1d10", desc: "Con save. 5ft radius."},
    {name: "Pass without Trace", dice: "-", type: "Stealth", category: "Spell", level: 2, desc: "+10 Stealth."},
    {name: "Phantasmal Force", dice: "1d6", type: "Psychic", category: "Spell", level: 2, desc: "Int save. Illusion damages."},
    {name: "Prayer of Healing", dice: "2d8", type: "Healing", category: "Spell", level: 2, scale_dice: "1d8", desc: "10 min cast time."},
    {name: "Protection from Poison", dice: "-", type: "Buff", category: "Spell", level: 2, desc: "Resist poison, cure poison."},
    {name: "Ray of Enfeeblement", dice: "-", type: "Debuff", category: "Spell", level: 2, desc: "Half damage str attacks."},
    {name: "Rope Trick", dice: "-", type: "Utility", category: "Spell", level: 2, desc: "Hiding space."},
    {name: "Scorching Ray", dice: "2d6", type: "Fire", category: "Spell", level: 2, scale_dice: "2d6", desc: "3 rays."},
    {name: "See Invisibility", dice: "-", type: "Sense", category: "Spell", level: 2, desc: "See invisible."},
    {name: "Shatter", dice: "3d8", type: "Thunder", category: "Spell", level: 2, scale_dice: "1d8", desc: "Con save area dmg."},
    {name: "Silence", dice: "-", type: "Quiet", category: "Spell", level: 2, desc: "No sound/casting."},
    {name: "Spider Climb", dice: "-", type: "Movement", category: "Spell", level: 2, desc: "Climb walls."},
    {name: "Spike Growth", dice: "2d4", type: "Piercing", category: "Spell", level: 2, desc: "Diff terrain, damage on move."},
    {name: "Spiritual Weapon", dice: "1d8", type: "Force", category: "Spell", level: 2, action_type: "Bonus Action", scale_dice: "1d8", desc: "Floating weapon attacks."},
    {name: "Suggestion", dice: "-", type: "Control", category: "Spell", level: 2, desc: "Wis save. Command."},
    {name: "Warding Bond", dice: "-", type: "Buff", category: "Spell", level: 2, desc: "+1 AC/Save, split damage."},
    {name: "Web", dice: "-", type: "Restrain", category: "Spell", level: 2, desc: "Dex save restrain."},
    {name: "Zone of Truth", dice: "-", type: "Social", category: "Spell", level: 2, desc: "Can't lie."},
    {name: "Animate Dead", dice: "-", type: "Summon", category: "Spell", level: 3, desc: "Create zombie/skeleton."},
    {name: "Aura of Vitality", dice: "2d6", type: "Healing", category: "Spell", level: 3, desc: "BA heal 2d6 per turn."},
    {name: "Beacon of Hope", dice: "-", type: "Buff", category: "Spell", level: 3, desc: "Max healing, adv wis saves."},
    {name: "Bestow Curse", dice: "-", type: "Debuff", category: "Spell", level: 3, desc: "Disadv, extra dmg, or inaction."},
    {name: "Blink", dice: "-", type: "Defense", category: "Spell", level: 3, desc: "50% chance vanish."},
    {name: "Call Lightning", dice: "3d10", type: "Lightning", category: "Spell", level: 3, scale_dice: "1d10", desc: "Dex save area."},
    {name: "Clairvoyance", dice: "-", type: "Divination", category: "Spell", level: 3, desc: "See/Hear remote location."},
    {name: "Conjure Animals", dice: "-", type: "Summon", category: "Spell", level: 3, desc: "Summon fey beasts."},
    {name: "Counterspell", dice: "-", type: "Negate", category: "Spell", level: 3, action_type: "Reaction", desc: "Stop spell cast."},
    {name: "Create Food and Water", dice: "-", type: "Utility", category: "Spell", level: 3, desc: "Feed 15 people."},
    {name: "Daylight", dice: "-", type: "Light", category: "Spell", level: 3, desc: "Bright light 60ft."},
    {name: "Dispel Magic", dice: "-", type: "End Spell", category: "Spell", level: 3, desc: "End magical effects."},
    {name: "Fear", dice: "-", type: "Control", category: "Spell", level: 3, desc: "Wis save. Frightened drop items."},
    {name: "Feign Death", dice: "-", type: "Utility", category: "Spell", level: 3, desc: "Appear dead."},
    {name: "Fireball", dice: "8d6", type: "Fire", category: "Spell", level: 3, scale_dice: "1d6", desc: "Dex save. 20ft radius."},
    {name: "Fly", dice: "-", type: "Flight", category: "Spell", level: 3, desc: "60ft fly speed."},
    {name: "Gaseous Form", dice: "-", type: "Utility", category: "Spell", level: 3, desc: "Mist form."},
    {name: "Glyph of Warding", dice: "5d8", type: "Explosive", category: "Spell", level: 3, desc: "Trap."},
    {name: "Haste", dice: "-", type: "Speed", category: "Spell", level: 3, desc: "+2 AC, double speed, extra action."},
    {name: "Hunger of Hadar", dice: "2d6", type: "Cold", category: "Spell", level: 3, desc: "Blindness, Cold/Acid dmg."},
    {name: "Hypnotic Pattern", dice: "-", type: "Control", category: "Spell", level: 3, desc: "Wis save. Incapacitated."},
    {name: "Lightning Bolt", dice: "8d6", type: "Lightning", category: "Spell", level: 3, scale_dice: "1d6", desc: "Dex save. Line."},
    {name: "Magic Circle", dice: "-", type: "Protection", category: "Spell", level: 3, desc: "Trap/block creature types."},
    {name: "Major Image", dice: "-", type: "Illusion", category: "Spell", level: 3, desc: "Complex illusion."},
    {name: "Mass Healing Word", dice: "1d4", type: "Healing", category: "Spell", level: 3, action_type: "Bonus Action", scale_dice: "1d4", desc: "Heal 6 creatures."},
    {name: "Meld into Stone", dice: "-", type: "Utility", category: "Spell", level: 3, desc: "Hide in stone."},
    {name: "Nondetection", dice: "-", type: "Utility", category: "Spell", level: 3, desc: "Hide from divination."},
    {name: "Phantom Steed", dice: "-", type: "Summon", category: "Spell", level: 3, desc: "Fast horse."},
    {name: "Plant Growth", dice: "-", type: "Control", category: "Spell", level: 3, desc: "Overgrowth."},
    {name: "Protection from Energy", dice: "-", type: "Resist", category: "Spell", level: 3, desc: "Resist one type."},
    {name: "Remove Curse", dice: "-", type: "Cure", category: "Spell", level: 3, desc: "End curse/attunement."},
    {name: "Revivify", dice: "-", type: "Resurrect", category: "Spell", level: 3, desc: "Revive within 1 min."},
    {name: "Sending", dice: "-", type: "Comm", category: "Spell", level: 3, desc: "Message anywhere."},
    {name: "Sleet Storm", dice: "-", type: "Control", category: "Spell", level: 3, desc: "Prone/Obscured."},
    {name: "Slow", dice: "-", type: "Debuff", category: "Spell", level: 3, desc: "No reactions, half speed."},
    {name: "Speak with Dead", dice: "-", type: "Info", category: "Spell", level: 3, desc: "Ask 5 questions."},
    {name: "Speak with Plants", dice: "-", type: "Comm", category: "Spell", level: 3, desc: "Communicate/Move plants."},
    {name: "Spirit Guardians", dice: "3d8", type: "Radiant", category: "Spell", level: 3, scale_dice: "1d8", desc: "Wis save. Area dmg around you."},
    {name: "Stinking Cloud", dice: "-", type: "Control", category: "Spell", level: 3, desc: "Lose action retching."},
    {name: "Tongues", dice: "-", type: "Comm", category: "Spell", level: 3, desc: "Understand all languages."},
    {name: "Vampiric Touch", dice: "3d6", type: "Necrotic", category: "Spell", level: 3, scale_dice: "1d6", desc: "Heal half dmg dealt."},
    {name: "Water Breathing", dice: "-", type: "Utility", category: "Spell", level: 3, desc: "Breathe water 24h."},
    {name: "Water Walk", dice: "-", type: "Utility", category: "Spell", level: 3, desc: "Walk on liquid."},
    {name: "Wind Wall", dice: "3d8", type: "Bludgeoning", category: "Spell", level: 3, desc: "Block arrows."},
    {name: "Arcane Eye", dice: "-", type: "Divination", category: "Spell", level: 4, desc: "Invisible eye scout."},
    {name: "Banishment", dice: "-", type: "Control", category: "Spell", level: 4, desc: "Cha save. Banish."},
    {name: "Blight", dice: "8d8", type: "Necrotic", category: "Spell", level: 4, scale_dice: "1d8", desc: "Con save."},
    {name: "Confusion", dice: "-", type: "Control", category: "Spell", level: 4, desc: "Wis save. Random acts."},
    {name: "Conjure Minor Elementals", dice: "-", type: "Summon", category: "Spell", level: 4, desc: "Summon elementals."},
    {name: "Conjure Woodland Beings", dice: "-", type: "Summon", category: "Spell", level: 4, desc: "Summon fey."},
    {name: "Control Water", dice: "-", type: "Control", category: "Spell", level: 4, desc: "Flood/Part water."},
    {name: "Death Ward", dice: "-", type: "Protection", category: "Spell", level: 4, desc: "Prevent death once."},
    {name: "Dimension Door", dice: "-", type: "Teleport", category: "Spell", level: 4, desc: "500ft teleport."},
    {name: "Divination", dice: "-", type: "Info", category: "Spell", level: 4, desc: "Ask god question."},
    {name: "Dominate Beast", dice: "-", type: "Control", category: "Spell", level: 4, desc: "Control animal."},
    {name: "Fabricate", dice: "-", type: "Creation", category: "Spell", level: 4, desc: "Create item."},
    {name: "Fire Shield", dice: "-", type: "Buff", category: "Spell", level: 4, desc: "Resist fire/cold, dmg attacker."},
    {name: "Freedom of Movement", dice: "-", type: "Buff", category: "Spell", level: 4, desc: "Ignore paralyze/restrain."},
    {name: "Giant Insect", dice: "-", type: "Transmute", category: "Spell", level: 4, desc: "Enlarge bugs."},
    {name: "Greater Invisibility", dice: "-", type: "Buff", category: "Spell", level: 4, desc: "Stay invisible when attacking."},
    {name: "Guardian of Faith", dice: "20", type: "Radiant", category: "Spell", level: 4, desc: "Stationary guardian."},
    {name: "Hallucinatory Terrain", dice: "-", type: "Illusion", category: "Spell", level: 4, desc: "Fake terrain."},
    {name: "Ice Storm", dice: "2d8", type: "Bludgeoning", category: "Spell", level: 4, scale_dice: "1d8", desc: "Hail + 4d6 cold."},
    {name: "Locate Creature", dice: "-", type: "Detection", category: "Spell", level: 4, desc: "Find creature."},
    {name: "Phantasmal Killer", dice: "4d10", type: "Psychic", category: "Spell", level: 4, scale_dice: "1d10", desc: "Fear dmg over time."},
    {name: "Polymorph", dice: "-", type: "Transform", category: "Spell", level: 4, desc: "Turn into beast."},
    {name: "Private Sanctum", dice: "-", type: "Utility", category: "Spell", level: 4, desc: "Block divination/teleport."},
    {name: "Resilient Sphere", dice: "-", type: "Protection", category: "Spell", level: 4, desc: "Invulnerable bubble."},
    {name: "Secret Chest", dice: "-", type: "Utility", category: "Spell", level: 4, desc: "Hide chest in ethereal."},
    {name: "Stone Shape", dice: "-", type: "Utility", category: "Spell", level: 4, desc: "Reshape stone."},
    {name: "Stoneskin", dice: "-", type: "Resist", category: "Spell", level: 4, desc: "Resist non-magic physical."},
    {name: "Wall of Fire", dice: "5d8", type: "Fire", category: "Spell", level: 4, scale_dice: "1d8", desc: "Line or ring."},
    {name: "Animate Objects", dice: "1d4+4", type: "Bludgeoning", category: "Spell", level: 5, desc: "Animated swarm."},
    {name: "Antilife Shell", dice: "-", type: "Protection", category: "Spell", level: 5, desc: "Living can't pass."},
    {name: "Awaken", dice: "-", type: "Charm", category: "Spell", level: 5, desc: "Sentient plant/beast."},
    {name: "Cloudkill", dice: "5d8", type: "Poison", category: "Spell", level: 5, scale_dice: "1d8", desc: "Moving poison fog."},
    {name: "Commune", dice: "-", type: "Divination", category: "Spell", level: 5, desc: "3 questions."},
    {name: "Commune with Nature", dice: "-", type: "Divination", category: "Spell", level: 5, desc: "Info on surroundings."},
    {name: "Cone of Cold", dice: "8d8", type: "Cold", category: "Spell", level: 5, scale_dice: "1d8", desc: "60ft cone."},
    {name: "Conjure Elemental", dice: "-", type: "Summon", category: "Spell", level: 5, desc: "Summon elemental."},
    {name: "Contact Other Plane", dice: "-", type: "Divination", category: "Spell", level: 5, desc: "Int save or insane."},
    {name: "Contagion", dice: "-", type: "Disease", category: "Spell", level: 5, desc: "Inflict disease."},
    {name: "Creation", dice: "-", type: "Utility", category: "Spell", level: 5, desc: "Create material object."},
    {name: "Dispel Evil and Good", dice: "-", type: "Protection", category: "Spell", level: 5, desc: "Banish/Protect."},
    {name: "Dominate Person", dice: "-", type: "Control", category: "Spell", level: 5, desc: "Control humanoid."},
    {name: "Dream", dice: "-", type: "Comm", category: "Spell", level: 5, desc: "Message in sleep."},
    {name: "Flame Strike", dice: "4d6", type: "Fire/Radiant", category: "Spell", level: 5, scale_dice: "1d6", desc: "Cylinder fire."},
    {name: "Geas", dice: "5d10", type: "Psychic", category: "Spell", level: 5, desc: "Command with penalty."},
    {name: "Greater Restoration", dice: "-", type: "Cure", category: "Spell", level: 5, desc: "End charm/petrify/curse."},
    {name: "Hallow", dice: "-", type: "Buff", category: "Spell", level: 5, desc: "Consecrate ground."},
    {name: "Hold Monster", dice: "-", type: "Paralyze", category: "Spell", level: 5, desc: "Paralyze any creature."},
    {name: "Insect Plague", dice: "4d10", type: "Piercing", category: "Spell", level: 5, scale_dice: "1d10", desc: "Area bugs."},
    {name: "Legend Lore", dice: "-", type: "Info", category: "Spell", level: 5, desc: "Lore about item/place."},
    {name: "Mass Cure Wounds", dice: "3d8", type: "Healing", category: "Spell", level: 5, scale_dice: "1d8", desc: "Heal 6 creatures."},
    {name: "Mislead", dice: "-", type: "Illusion", category: "Spell", level: 5, desc: "Invisible + Duplicate."},
    {name: "Modify Memory", dice: "-", type: "Control", category: "Spell", level: 5, desc: "Rewrite memory."},
    {name: "Passwall", dice: "-", type: "Utility", category: "Spell", level: 5, desc: "Tunnel through wall."},
    {name: "Planar Binding", dice: "-", type: "Control", category: "Spell", level: 5, desc: "Bind extraplanar."},
    {name: "Raise Dead", dice: "-", type: "Resurrect", category: "Spell", level: 5, desc: "Revive within 10 days."},
    {name: "Rary's Telepathic Bond", dice: "-", type: "Comm", category: "Spell", level: 5, desc: "Group telepathy."},
    {name: "Reincarnate", dice: "-", type: "Resurrect", category: "Spell", level: 5, desc: "New body."},
    {name: "Scrying", dice: "-", type: "Divination", category: "Spell", level: 5, desc: "Spy remote."},
    {name: "Seeming", dice: "-", type: "Illusion", category: "Spell", level: 5, desc: "Mass disguise."},
    {name: "Telekinesis", dice: "-", type: "Control", category: "Spell", level: 5, desc: "Move objects/creatures."},
    {name: "Teleportation Circle", dice: "-", type: "Transport", category: "Spell", level: 5, desc: "Teleport to circle."},
    {name: "Tree Stride", dice: "-", type: "Transport", category: "Spell", level: 5, desc: "Step between trees."},
    {name: "Wall of Force", dice: "-", type: "Barrier", category: "Spell", level: 5, desc: "Indestructible wall."},
    {name: "Wall of Stone", dice: "-", type: "Barrier", category: "Spell", level: 5, desc: "Solid wall."},
    {name: "Arcane Gate", dice: "-", type: "Transport", category: "Spell", level: 6, desc: "Two portals."},
    {name: "Blade Barrier", dice: "6d10", type: "Slashing", category: "Spell", level: 6, desc: "Wall of blades."},
    {name: "Chain Lightning", dice: "10d8", type: "Lightning", category: "Spell", level: 6, scale_dice: "1d8", desc: "Jumps to 3 targets."},
    {name: "Circle of Death", dice: "8d6", type: "Necrotic", category: "Spell", level: 6, scale_dice: "2d6", desc: "Huge radius."},
    {name: "Disintegrate", dice: "10d6+40", type: "Force", category: "Spell", level: 6, scale_dice: "3d6", desc: "Dusts target."},
    {name: "Eyebite", dice: "-", type: "Debuff", category: "Spell", level: 6, desc: "Sleep/Fear/Sicken."},
    {name: "Find the Path", dice: "-", type: "Divination", category: "Spell", level: 6, desc: "Know way to loc."},
    {name: "Flesh to Stone", dice: "-", type: "Transmute", category: "Spell", level: 6, desc: "Petrify."},
    {name: "Forbiddance", dice: "-", type: "Protection", category: "Spell", level: 6, desc: "Block teleport/types."},
    {name: "Globe of Invulnerability", dice: "-", type: "Protection", category: "Spell", level: 6, desc: "Block low level spells."},
    {name: "Guards and Wards", dice: "-", type: "Trap", category: "Spell", level: 6, desc: "Fortify area."},
    {name: "Harm", dice: "14d6", type: "Necrotic", category: "Spell", level: 6, desc: "Reduce max HP."},
    {name: "Heal", dice: "70", type: "Healing", category: "Spell", level: 6, scale_dice: "10", desc: "Heal 70, cure disease."},
    {name: "Heroes' Feast", dice: "-", type: "Buff", category: "Spell", level: 6, desc: "Immune poison/fear, max HP."},
    {name: "Instant Summons", dice: "-", type: "Utility", category: "Spell", level: 6, desc: "Summon item."},
    {name: "Irresistible Dance", dice: "-", type: "Control", category: "Spell", level: 6, desc: "Must dance."},
    {name: "Mass Suggestion", dice: "-", type: "Control", category: "Spell", level: 6, desc: "Suggest 12 creatures."},
    {name: "Move Earth", dice: "-", type: "Transmute", category: "Spell", level: 6, desc: "Reshape terrain."},
    {name: "Planar Ally", dice: "-", type: "Summon", category: "Spell", level: 6, desc: "Pay entity for aid."},
    {name: "Programmed Illusion", dice: "-", type: "Illusion", category: "Spell", level: 6, desc: "Scripted illusion."},
    {name: "Sunbeam", dice: "6d8", type: "Radiant", category: "Spell", level: 6, desc: "Line of light."},
    {name: "True Seeing", dice: "-", type: "Divination", category: "Spell", level: 6, desc: "See all."},
    {name: "Wall of Ice", dice: "10d6", type: "Cold", category: "Spell", level: 6, desc: "Ice wall."},
    {name: "Wall of Thorns", dice: "7d8", type: "Piercing", category: "Spell", level: 6, desc: "Thorn wall."},
    {name: "Wind Walk", dice: "-", type: "Transport", category: "Spell", level: 6, desc: "Turn into clouds."},
    {name: "Word of Recall", dice: "-", type: "Transport", category: "Spell", level: 6, desc: "Teleport to sanctuary."},
    {name: "Arcane Sword", dice: "3d10", type: "Force", category: "Spell", level: 7, desc: "Floating sword."},
    {name: "Conjure Celestial", dice: "-", type: "Summon", category: "Spell", level: 7, desc: "Summon celestial."},
    {name: "Delayed Blast Fireball", dice: "12d6", type: "Fire", category: "Spell", level: 7, desc: "Explodes later."},
    {name: "Divine Word", dice: "-", type: "Banish", category: "Spell", level: 7, desc: "Banish/Kill by HP."},
    {name: "Etherealness", dice: "-", type: "Transport", category: "Spell", level: 7, desc: "Enter Ethereal."},
    {name: "Finger of Death", dice: "7d8+30", type: "Necrotic", category: "Spell", level: 7, desc: "Create zombie."},
    {name: "Fire Storm", dice: "7d10", type: "Fire", category: "Spell", level: 7, desc: "Large fire area."},
    {name: "Forcecage", dice: "-", type: "Trap", category: "Spell", level: 7, desc: "Unbreakable cage."},
    {name: "Mirage Arcane", dice: "-", type: "Illusion", category: "Spell", level: 7, desc: "Alter terrain."},
    {name: "Magnificent Mansion", dice: "-", type: "Utility", category: "Spell", level: 7, desc: "Safe haven."},
    {name: "Plane Shift", dice: "-", type: "Transport", category: "Spell", level: 7, desc: "Travel planes/Banish."},
    {name: "Prismatic Spray", dice: "10d6", type: "Random", category: "Spell", level: 7, desc: "Random effects."},
    {name: "Project Image", dice: "-", type: "Illusion", category: "Spell", level: 7, desc: "Hologram."},
    {name: "Regenerate", dice: "-", type: "Healing", category: "Spell", level: 7, desc: "Regrow limbs."},
    {name: "Resurrection", dice: "-", type: "Resurrect", category: "Spell", level: 7, desc: "Revive dead."},
    {name: "Reverse Gravity", dice: "-", type: "Control", category: "Spell", level: 7, desc: "Fall upwards."},
    {name: "Sequester", dice: "-", type: "Utility", category: "Spell", level: 7, desc: "Hide object/creature."},
    {name: "Simulacrum", dice: "-", type: "Duplicate", category: "Spell", level: 7, desc: "Snow duplicate."},
    {name: "Symbol", dice: "-", type: "Trap", category: "Spell", level: 7, desc: "Rune trap."},
    {name: "Teleport", dice: "-", type: "Transport", category: "Spell", level: 7, desc: "Teleport anywhere."},
    {name: "Animal Shapes", dice: "-", type: "Transform", category: "Spell", level: 8, desc: "Mass polymorph."},
    {name: "Antimagic Field", dice: "-", type: "Protection", category: "Spell", level: 8, desc: "No magic zone."},
    {name: "Antipathy/Sympathy", dice: "-", type: "Control", category: "Spell", level: 8, desc: "Attract/Repel."},
    {name: "Clone", dice: "-", type: "Necromancy", category: "Spell", level: 8, desc: "Backup body."},
    {name: "Control Weather", dice: "-", type: "Utility", category: "Spell", level: 8, desc: "Change weather."},
    {name: "Demiplane", dice: "-", type: "Transport", category: "Spell", level: 8, desc: "Private room."},
    {name: "Dominate Monster", dice: "-", type: "Control", category: "Spell", level: 8, desc: "Control creature."},
    {name: "Earthquake", dice: "-", type: "Destruction", category: "Spell", level: 8, desc: "Destroy structures."},
    {name: "Feeblemind", dice: "4d6", type: "Psychic", category: "Spell", level: 8, desc: "Reduce Int/Cha to 1."},
    {name: "Glibness", dice: "-", type: "Social", category: "Spell", level: 8, desc: "Auto 15 on Cha checks."},
    {name: "Holy Aura", dice: "-", type: "Buff", category: "Spell", level: 8, desc: "Advantage and Protection."},
    {name: "Incendiary Cloud", dice: "10d8", type: "Fire", category: "Spell", level: 8, desc: "Moving fire cloud."},
    {name: "Maze", dice: "-", type: "Banish", category: "Spell", level: 8, desc: "Banish to maze."},
    {name: "Mind Blank", dice: "-", type: "Protection", category: "Spell", level: 8, desc: "Immune psychic/divination."},
    {name: "Power Word Stun", dice: "-", type: "Control", category: "Spell", level: 8, desc: "Stun if < 150HP."},
    {name: "Sunburst", dice: "12d6", type: "Radiant", category: "Spell", level: 8, desc: "Huge radiant area."},
    {name: "Telepathy", dice: "-", type: "Comm", category: "Spell", level: 8, desc: "Unlimited range."},
    {name: "Tsunami", dice: "6d10", type: "Bludgeoning", category: "Spell", level: 8, desc: "Wall of water."},
    {name: "Astral Projection", dice: "-", type: "Transport", category: "Spell", level: 9, desc: "Travel astrally."},
    {name: "Foresight", dice: "-", type: "Buff", category: "Spell", level: 9, desc: "Advantage on everything."},
    {name: "Gate", dice: "-", type: "Transport", category: "Spell", level: 9, desc: "Portal to plane."},
    {name: "Imprisonment", dice: "-", type: "Control", category: "Spell", level: 9, desc: "Permanent trap."},
    {name: "Mass Heal", dice: "700", type: "Healing", category: "Spell", level: 9, desc: "700 HP pool."},
    {name: "Meteor Swarm", dice: "40d6", type: "Fire/Bludg", category: "Spell", level: 9, desc: "4 meteors."},
    {name: "Power Word Heal", dice: "-", type: "Healing", category: "Spell", level: 9, desc: "Full heal."},
    {name: "Power Word Kill", dice: "100", type: "Instant Death", category: "Spell", level: 9, desc: "Kill if < 100HP."},
    {name: "Prismatic Wall", dice: "-", type: "Barrier", category: "Spell", level: 9, desc: "Multi-layer wall."},
    {name: "Shapechange", dice: "-", type: "Transform", category: "Spell", level: 9, desc: "Become any creature."},
    {name: "Storm of Vengeance", dice: "2d6", type: "Thunder", category: "Spell", level: 9, desc: "Global storm."},
    {name: "Time Stop", dice: "-", type: "Utility", category: "Spell", level: 9, desc: "Take 1d4+1 turns."},
    {name: "True Polymorph", dice: "-", type: "Transform", category: "Spell", level: 9, desc: "Permanent change."},
    {name: "True Resurrection", dice: "-", type: "Resurrect", category: "Spell", level: 9, desc: "Revive anyone."},
    {name: "Weird", dice: "4d10", type: "Psychic", category: "Spell", level: 9, desc: "Mass fear/damage."},
    {name: "Wish", dice: "-", type: "Unlimited", category: "Spell", level: 9, desc: "Alter reality."}
];

const ALL_ACTIONS = ALL_WEAPONS.concat(ALL_SPELLS).concat(SUBCLASS_FEATURES);